### ISSUE TITLE
加一个文本超出鼠标悬停展示全部，没超出则不展示

### ISSUE THREAD

**Issue by regg1e** [JoeWrights/v-text-ellipsis#3]
加一个文本超出鼠标悬停展示全部，没超出则不展示

**Comment by JoeWrights** [comment]
> 加一个文本超出鼠标悬停展示全部，没超出则不展示

[这个可以，不过也可以通过控制`isLimitHeight`这个属性实现你想要的效果，看[这里](https://joewrights.github.io/v-text-ellipsis/)第三个例子

**Comment by regg1e** [comment]
厉害！
